version: '3.1'

services:

  mongo:
    image: aashreys/mongo-auth:latest
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=admin123
      - MONGODB_APPLICATION_DATABASE=patagonian
      - MONGODB_APPLICATION_USER=patagonian
      - MONGODB_APPLICATION_PASS=patagonian
    ports:
      - 27017:27017
    networks:
      - default

  spring-boot:
    build:
      context: ./
      dockerfile: spring-boot-app-docker/Dockerfile
    depends_on:
      - mongo
    ports:
      - 8080:8080
    networks:
      - default

networks:
  default:
    external:
       name: patagonian_net
