version: '3.1'

services:

  mongo:
    image: aashreys/mongo-auth:latest
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=admin123
      - MONGODB_APPLICATION_DATABASE=patagonian
      - MONGODB_APPLICATION_USER=patagonian
      - MONGODB_APPLICATION_PASS=patagonian
    ports:
      - 27017:27017
    volumes:
      - ./mongo-volume:/data/db
    networks:
      - default

networks:
  default:
    external:
       name: patagonian_net
